publish_to: none
name: weather_forecast_controller
description: Minerva application.
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  minerva_controller: ^0.9.0
  minerva: ^0.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  minerva_controller_generator: ^0.9.0
  minerva_controller_annotation: ^0.9.0
